const fitnessData = {
  "exercitii-upper": [
  {
    slug: "push-ups",
    title: "Push-ups ",
    description: "Flotările sunt un exercițiu clasic care lucrează pieptul, umerii și tricepsul. Poți varia dificultatea prin modificarea poziției mâinilor sau prin adăugarea de greutăți.",
    image: "https://www.realsimple.com/thmb/-PW_i-RMLQ4cj3-okjqccGGUock=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/health-benefits-of-pushups-GettyImages-498315681-7008d40842444270868c88b516496884.jpg",
    category: "exercitii-upper", 
  },
  {
    slug: "dumbbell-shoulder-press",
    title: "Dumbbell Shoulder Press ",
    description: "Acest exercițiu se concentrează pe dezvoltarea umerilor, ajutând la creșterea forței și stabilității acestora. Se poate face stând pe un scaun sau în picioare, cu ganterele în mâini.",
    image: "https://sportivetricksstorage.blob.core.windows.net/images/articles/training/technique/db-shoulder-press/1-man-pressing.webp",
    category: "exercitii-upper", 
  },
  {
    slug: "bent-over rows",
    title: "Bent-over Rows",
    description: "Întărește spatele superior și bicepsul cu acest exercițiu, concentrându-te pe mișcarea controlată și postura corectă.",
    image: "https://d1lcvt77zgh63s.cloudfront.net/wp-content/uploads/2023/09/barbell-bent-over-row.jpg",
    category: "exercitii-upper", 
  },
  {
    slug: "triceps-dips",
    title: "Triceps Dips",
    description: "Dipsurile sunt o metodă excelentă de a lucra tricepsul, fiind un exercițiu ce poate fi realizat pe o bancă sau o margine a unei suprafețe stabile.",
    image: "https://www.g4physio.co.uk/wp-content/uploads/2016/11/IMG_0604.jpg",
    category: "exercitii-upper", 
  },
  {
    slug: "lateral-raises",
    title: "Lateral Raises",
    description: "Acest exercițiu vizează umerii laterali, oferind acea formă rotundă și definită umerilor. Poți să le faci cu gantere ușoare pentru a evita supraîncărcarea.",
    image: "https://i0.wp.com/www.strengthlog.com/wp-content/uploads/2024/12/dumbbell-lateral-raise-vs.-cable-lateral-raise-1-scaled.jpg?fit=2560%2C1707&ssl=1",
    category: "exercitii-upper", 
  },
  {
    slug: "chest-press",
    title: "Chest Press",
    description: "Similar cu flotările, dar executat pe bancă, acest exercițiu vizează pieptul și umerii, ajutând la întărirea și tonifierea acestora.",
    image: "https://i0.wp.com/www.strengthlog.com/wp-content/uploads/2022/02/Chest-Press-Machine.jpg?fit=2016%2C1344&ssl=1",
    category: "exercitii-upper", 
  },
  {
    slug: "bicep-curls",
    title: "Bicep Curls",
    description: "Un exercițiu excelent pentru a construi bicepsul, flexiile cu gantere sunt simple, dar eficiente, și pot fi făcute și în poziție șezândă sau în picioare.",
    image: "https://images.healthshots.com/healthshots/en/uploads/2024/09/10173919/Bicep-curl-3.jpg",
    category: "exercitii-upper", 
  },
  ],
  "exercitii-lower": [
  {
    slug: "squats",
    title: "Squats ",
    description: "Genuflexiunile sunt fundamentale pentru întărirea coapselor, fesierilor și gambelor. Poți varia dificultatea prin adăugarea de greutăți sau prin adâncirea mișcării.",
    image: "https://www.verywellfit.com/thmb/RME17zorpHqz5CI_XW4lkFwTd8A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/young-female-athlete-lifting-kettle-bell-while-crouching-in-gym-1284730860-a3f1a3d2b2d14311bcbf4754f5e0effa.jpg",
    category: "exercitii-lower", 
  },
  {
    slug: "lunges",
    title: "Lunges",
    description: "Exercițiu eficient pentru a lucra coapsele și fesierii, fandările sunt excelente pentru echilibru și stabilitate. Pot fi făcute și pe loc sau în deplasare.",
    image: "https://images.healthshots.com/healthshots/en/uploads/2024/05/02174153/Lunges.jpg",
    category: "exercitii-lower", 
  },
  {
    slug: "glute bridges",
    title: "Glute Bridges",
    description: "Acest exercițiu se concentrează pe întărirea fesierilor și a zonei inferioare a spatelui. Ideal pentru îmbunătățirea posturii și tonifierii regiunii.",
    image: "https://media1.popsugar-assets.com/files/thumbor/yMI6InOmnA7DfQk84CZsJzEE3cU=/45x757:1376x1456/fit-in/1456x1456/filters:format_auto():quality(85):upscale()/2024/04/22/755/n/1922729/33380390662699744964a6.05278932_.jpg",
    category: "exercitii-lower", 
  },
  {
    slug: "deadlifts",
    title: "Deadlifts",
    description: "Îndreptările sunt excelente pentru întărirea fesierilor, coapselor și spatelui inferior. Asigură-te că execuți mișcarea corect pentru a preveni accidentările.",
    image: "https://storage.googleapis.com/flex-web-media-prod/content/images/wp-content/uploads/2024/05/woman-deadlifting.jpg",
    category: "exercitii-lower", 
  },
  {
    slug: "leg-curls",
    title: "Leg Curls",
    description: "Acest exercițiu lucrează în special mușchii posteriori ai coapselor, fiind o opțiune bună pentru tonifierea zonei.",
    image: "https://barbend.com/wp-content/uploads/2022/10/Untitled-design-2022-10-13T113544.788.png",
    category: "exercitii-lower", 
  },
  {
    slug: "step-ups",
    title: "Step-ups",
    description: "Step-up-urile sunt excelente pentru coapse și fesieri, oferind un antrenament eficient pentru picioare. Se poate adăuga greutate pentru intensitate suplimentară.",
    image: "https://app-media.fitbod.me/v2/128/images/landscape/0_960x540.jpg",
    category: "exercitii-lower", 
  },
  {
    slug: "calf-raises",
    title: "Calf Raises",
    description: "Pentru a tonifia gambelor, ridicările pe vârfuri sunt foarte eficiente. Le poți face pe o suprafață mai înaltă pentru a crește gama de mișcare.",
    image: "https://hips.hearstapps.com/hmg-prod/images/screen-shot-2023-12-21-at-5-01-33-pm-1-658c642a2bf8d.png?resize=980:*",
    category: "exercitii-lower", 
  },
  
],
  "apdomen" : [
  {
    slug: "plank",
    title: "Plank",
    description: "Un exercițiu excelent pentru întărirea întregului abdomen și stabilizarea core-ului. ",
    image: "https://www.mensjournal.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2MTM3MjE4NzA1NDAxMzQ5/planks_for_abs_main_0.jpg",
    category: "apdomen", 
  },
  {
    slug: "crunches",
    title: "Crunches",
    description: "Abdomenele sunt clasice pentru lucrul mușchilor superiori ai abdomenului. Asigură-te că faci mișcarea controlat pentru a maximiza rezultatele și a preveni accidentările.",
    image: "https://media.self.com/photos/5dfa77378873ee00093325ae/4:3/w_2560%2Cc_limit/GettyImages-498282756.jpg",
    category: "apdomen", 
  },
  {
    slug: "bicycle-crunches",
    title: "Bicycle Crunches",
    description: "Aceste abdomene lucrează atât partea superioară cât și inferioară a abdomenului, dar și oblicii. Sunt excelente pentru tonifierea întregii zone abdominale.",
    image: "https://steelsupplements.com/cdn/shop/articles/Bicycle_crunch_-_cover_-_shutterstock_1420680866_600x.jpg?v=1670162703",
    category: "apdomen", 
  },
  {
    slug: "russian-twists",
    title: "Russian Twists",
    description: "Un exercițiu excelent pentru oblici, acest mișcare ajută la îmbunătățirea mobilității și tonifierea mușchilor laterali ai abdomenului.",
    image: "https://breakingmuscle.com/wp-content/uploads/2022/11/Shutterstock_2166325891.jpg",
    category: "apdomen", 
  },
  {
    slug: "leg-raises",
    title: "Leg Raises",
    description: "Acest exercițiu vizează în special partea inferioară a abdomenului. Poți adăuga dificultate prin utilizarea unei mingi sau prin ridicarea picioarelor până la un unghi mai mare.",
    image: "https://i0.wp.com/www.muscleandfitness.com/wp-content/uploads/2013/03/Muscular-Man-Working-Out-His-Lower-Abs-With-Lying-Leg-Raises-Exercise.jpg?quality=86&strip=all",
    category: "apdomen", 
  },
  {
    slug: "flutter-kicks",
    title: "Flutter Kicks",
    description: "Un alt exercițiu pentru partea inferioară a abdomenului, flutter kicks sunt excelente pentru tonifierea zonei abdominale și îmbunătățirea flexibilității.",
    image: "https://cdn.media.amplience.net/i/thegymgroup/The_Gym_Group-Exercises-How_To_Do_Flutter_Kicks-Step_By_Step_4",
    category: "apdomen", 
  },
  {
    slug: "mountain-climbers",
    title: "Mountain Climbers",
    description: "Acest exercițiu este ideal pentru a lucra abdomenul, dar și pentru a îmbunătăți rezistența cardiovasculară. Se poate face rapid, într-un ritm alert, pentru a crește intensitatea.",
    image: "https://i.guim.co.uk/img/media/e7ee4fd3eca4df1346f46d762dbb74b03c61ac6e/1020_1075_3464_2078/500.jpg?quality=85&auto=format&fit=max&s=820135a6cec5fa7397510a0b1add2cca",
    category: "apdomen", 
  },
],
"secrete-gym" : [
  {
    slug: "secrete",
    title: "Adopta o forma corecta",
    description: "Cheia succesului în orice antrenament este să execuți mișcările corect. Fie că este vorba de genuflexiuni sau flotări, o formă incorectă poate duce la accidentări și la rezultate mai slabe. Încearcă să îți controlezi postura și să nu te grăbești.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFlyUq3FK4ZkG6AnB_TwNNneA5mncHpwI0PKAvpRWRGpzrT_WtTkIOLpJcZ8t9REJd9g8&usqp=CAU",
    category: "secrete-gym", 
  },
  {
    slug: "secrete",
    title: "Varietatea este cheia progresului",
    description: "Pentru a evita stagnarea și a continua să progresezi, este esențial să îți schimbi rutina de antrenament din când în când. Încearcă să variezi exercițiile, greutățile și numărul de seturi/repetări.",
    image: "https://www.steroizi.ro/media/3279/pauza-odihna-pentru-forta-si-putere.jpg",
    category: "secrete-gym",
  },
  {
    slug: "secrete",
    title: "Odihna este importanta",
    description: "Nu subestima puterea odihnei! Mușchii cresc și se repară în timpul perioadelor de odihnă. Asigură-te că îți dai corpului suficient timp pentru recuperare între antrenamente.",
    image: "https://www.worldclass.ro/wp-content/uploads/Picture1-1-1.jpg",
    category: "secrete-gym",
  },
  {
    slug: "secrete",
    title: "Progresia treptata",
    description: "Creșterea graduală a greutăților sau a intensității antrenamentului este esențială pentru a evita platoul de antrenament. Începe cu greutăți mai mici și crește-le pe măsură ce devii mai puternic.",
    image: "https://urbangym.ro/wp-content/uploads/2021/11/Ziua-de-brate-si-umeri-pentru-doamne.jpg",
    category: "secrete-gym",
  },
  {
    slug: "secrete",
    title: "Exercitiile compound sunt cele mai eficiente",
    description: "Exercițiile care lucrează mai multe grupuri musculare deodată (de exemplu, genuflexiunile, îndreptările sau flotările) sunt excelente pentru a construi forță și masă musculară. Acestea sunt mult mai eficiente decât exercițiile de izolare.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLl2pbCcRsvyavmp8aTaayWSLyfxJ1eposUQ&s",
    category: "secrete-gym", 
  },
  {
    slug: "secrete",
    title: "Nu neglija încalzirea si stretching-ul",
    description: "Înainte de orice antrenament, este esențial să îți încălzești mușchii. Acest lucru îți va îmbunătăți performanța și va preveni accidentările. De asemenea, stretching-ul după antrenament ajută la flexibilitate și recuperare.",
    image: "https://blog.nasm.org/hubfs/beginner-stretches.jpg",
    category: "secrete-gym",
  },
  {
    slug: "secrete",
    title: "Nutritia joaca un rol esential",
    description: "Dacă vrei să îți atingi obiectivele în sala de sport, alimentația corectă este crucială. Consumă suficiente proteine pentru a sprijini creșterea musculară și hidratarea este la fel de importantă pentru performanță.",
    image: "https://cardioprima.md//upload/files/alimentatie-sanatoasa.jpg",
    category: "secrete-gym",
  },
],
};

export default fitnessData;
